### ISSUE TITLE
panic on `ngs account status`

### ISSUE THREAD

**Issue by kung-foo** [ConnectEverything/ngs-cli#12]
```
$ ngs account status
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x951cde]

goroutine 1 [running]:
github.com/ConnectEverything/ngs/ngs/cmd.(*StatusParams).setDefaults(0xc00019c2d0, 0xc00016bc20, 0x54f154)
	/home/travis/gopath/src/github.com/ConnectEverything/ngs/ngs/cmd/account_status.go:79 +0xbe
github.com/ConnectEverything/ngs/ngs/cmd.createStatusCmd.func1(0xc0001c5680, 0x100c5f0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ConnectEverything/ngs/ngs/cmd/account_status.go:26 +0x33
github.com/spf13/cobra.(*Command).execute(0xc0001c5680, 0x100c5f0, 0x0, 0x0, 0xc0001c5680, 0x100c5f0)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xfe41e0, 0xc0000ba010, 0xb7c9c0, 0xc0000ba010)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xfe41e0, 0xb7c9c0, 0xc0000ba010)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	/home/travis/gopath/src/github.com/ConnectEverything/ngs/ngs/main.go:67 +0x2e9

$ ngs --version
ngs version 0.8.1

$ uname -a
Linux xxx 5.2.10-xanmod9 #1.190825 SMP PREEMPT Sun Aug 25 19:13:19 -03 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sasbury** [comment]
do you still see this if you do `ngs update` to get the latest 0.11.0?

**Comment by kung-foo** [comment]
Different issue now:

```
Error: "/home/jonathan/.nsc/nats/synadia" is not a valid configuration directory
Usage:
  ngs status [flags]

Flags:
  -h, --help   help for status

Global Flags:
  -n, --account-name string   set the account name, defaults to an interactive picker
  -d, --synadia-dir string    set the synadia operator directory, this should contain the operator JWT
```

If I do `ngs status -d ~/.ngs/nats/synadia/` then it works...

Btw, the reason that I didn't notice the update available message is because it shows up at the top of the cli output. Maybe also print it at the bottom?

**Comment by sasbury** [comment]
We did a simplification at 0.9 that we should probably keep in the release notes - take a look here https://github.com/ConnectEverything/ngs-cli/blob/master/release_notes/migrating_to_0_9.md for info on migrating ~/.ngs to ~/.nsc so that you can use nsc for most of your tasks.

Closing for now, please reopen if you are still having issues.
